# SmartCampus SwiftLint 설정

# 활성화할 규칙들
opt_in_rules:
  - array_init
  - closure_spacing
  - empty_count
  - explicit_init
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_alignment
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# 비활성화할 규칙들
disabled_rules:
  - todo
  - line_length  # 너무 엄격해서 개발 초기에는 끄기

# 제외할 폴더/파일들
excluded:
  - Pods
  - .build
  - DerivedData
  - Preview Content

# 포함할 폴더들 (선택사항)
included:
  - SmartCampus

# 파일 헤더 규칙 설정
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  SmartCampus
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/

# 라인 길이 설정 (활성화할 경우)
# line_length:
#   warning: 120
#   error: 140
#   ignores_urls: true
#   ignores_function_declarations: true
#   ignores_comments: true

# 함수 바디 길이 설정
function_body_length:
  warning: 60
  error: 100

# 타입 바디 길이 설정  
type_body_length:
  warning: 300
  error: 400

# 파일 길이 설정
file_length:
  warning: 500
  error: 800

# 중첩 타입 레벨 설정
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# 강제 언래핑 경고 설정
force_unwrapping: warning

# 암시적 언래핑 옵셔널 경고 설정
implicitly_unwrapped_optional: warning

# 커스텀 규칙
custom_rules:
  # MARK 주석 규칙
  mark_format:
    name: "MARK Format"
    regex: '\/\/ MARK: - .+'
    message: "MARK comments should follow format: // MARK: - Description"
    severity: warning
